export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-300">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Crimson+Pro:wght@400;600;700&family=DM+Sans:wght@400;500;700&display=swap');
        body { font-family: 'DM Sans', sans-serif; }
        .font-display { font-family: 'Crimson Pro', serif; }
      `}</style>

      <nav className="border-b border-slate-800/50 bg-slate-950/80 backdrop-blur-lg">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="font-display text-2xl font-bold">
            <span className="text-amber-500">Auto</span>
            <span className="text-slate-100">ReplyChat</span>
          </a>
          <a href="/" className="text-sm text-slate-400 hover:text-amber-500 transition-colors">
            ← Back to Home
          </a>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="font-display text-4xl md:text-5xl font-bold text-slate-100 mb-4">Terms of Service</h1>
        <p className="text-slate-500 mb-12">Last updated: February 2026</p>

        <div className="space-y-10 leading-relaxed">
          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">1. Agreement to Terms</h2>
            <p>By accessing or using AutoReplyChat, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the service.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">2. Description of Service</h2>
            <p>AutoReplyChat is an AI-powered customer support platform that allows businesses to create and deploy chatbots on their websites. The service includes document training, lead capture, conversation management, and a customisable chat widget.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">3. Account Registration</h2>
            <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorised use of your account.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">4. Free Trial</h2>
            <p>New accounts receive a 30-day free trial with full access to all features. At the end of the trial period, you must subscribe to a paid plan to continue using the service. We reserve the right to modify or discontinue the free trial at any time.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">5. Pricing and Payment</h2>
            <p>Paid subscriptions are billed monthly at the rate displayed at the time of purchase. All fees are non-refundable except where required by law. We reserve the right to change pricing with 30 days' notice. You may cancel your subscription at any time, and your access will continue until the end of the current billing period.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">6. Acceptable Use</h2>
            <p className="mb-4">You agree not to use AutoReplyChat to:</p>
            <p>Upload or distribute content that is unlawful, harmful, threatening, abusive, defamatory, or otherwise objectionable. Attempt to gain unauthorised access to other users' accounts or data. Use the service to send spam or unsolicited communications. Interfere with or disrupt the service or its infrastructure. Violate any applicable laws or regulations. Impersonate any person or entity, or misrepresent your affiliation with any person or entity.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">7. Your Content</h2>
            <p>You retain ownership of all content you upload to the platform. By uploading content, you grant us a limited licence to process, store, and use that content solely for the purpose of providing the AutoReplyChat service to you. We will not share your content with other customers or use it for any purpose other than operating your chatbot.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">8. AI-Generated Responses</h2>
            <p>Chatbot responses are generated by artificial intelligence based on the content you provide. While we strive for accuracy, AI-generated responses may occasionally contain errors or inaccuracies. You are responsible for reviewing and ensuring the appropriateness of your chatbot's responses. We are not liable for any decisions made based on AI-generated content.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">9. Service Availability</h2>
            <p>We aim to provide a reliable service but do not guarantee uninterrupted availability. We may perform scheduled maintenance or updates that temporarily affect service availability. We are not liable for any downtime or service interruptions.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, AutoReplyChat shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the service.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">11. Termination</h2>
            <p>We may suspend or terminate your account if you violate these terms. You may close your account at any time by contacting us. Upon termination, your data will be deleted within 30 days unless we are required by law to retain it.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">12. Changes to Terms</h2>
            <p>We may update these terms from time to time. We will notify you of any material changes by email or through the service. Your continued use of AutoReplyChat after changes take effect constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">13. Governing Law</h2>
            <p>These terms are governed by the laws of England and Wales. Any disputes arising from these terms or your use of the service shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-bold text-slate-100 mb-4">14. Contact</h2>
            <p>For any questions about these terms, please contact us at:</p>
            <p className="mt-2 text-slate-100">Email: mick@autoreplychat.com</p>
            <p className="text-slate-100">Phone: 07501 439406</p>
          </section>
        </div>
      </div>

      <footer className="border-t border-slate-800/50 py-8 mt-16">
        <div className="max-w-4xl mx-auto px-6 text-center text-sm text-slate-500">
          © 2026 AutoReplyChat. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
